# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/perl

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y libmoose-perl libreadonly-perl liblist-moreutils-perl libmodule-install-perl libtest-deep-perl libtest-exception-perl libtest-mockmodule-perl libtest-output-perl
          - perl Makefile.PL
          - make test
